name: CI & CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setupt node
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    
    - name: Building project
      run: |
        npm ci
        npm run test
        npm run build
        
    - name: Saving in cache
      uses: actions/cache@v2
      with:
        key: ${{ github.sha }}-build
        path: |
          ./build
          ./Dockerfile
          ./nginx.conf

  deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    needs: build
    
    steps:
    - name: Restoring from cache
      uses: actions/cache@v2
      with:
        key: ${{ github.sha }}-build
        path: |
          ./build
          ./Dockerfile
          ./nginx.conf
    
    - name: Configuring ssh
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        cat >> ~/.ssh/config <<END
        Host remote
          HostName $SSH_HOST
          Port $SSH_PORT
          User $SSH_USER
          IdentityFile ~/.ssh/id_rsa
          StrictHostKeyChecking no
        END
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
    
    - name: Creating project folder
      run: ssh remote 'mkdir -p ~/segoqu.com/blog-web'
    
    - name: Copying build
      run: rsync -az ./build remote:~/segoqu.com/blog-web
    
    - name: Copying Dockerfile and nginx.conf
      run: |
        rsync -z ./Dockerfile remote:~/segoqu.com/blog-web/Dockerfile
        rsync -z ./nginx.conf remote:~/segoqu.com/blog-web/nginx.conf
    
    - name: Running docker
      run: |
        ssh remote 'docker-compose -f ~/segoqu.com build blog-web'
        ssh remote 'docker-compose -f ~/segoqu.com --no-deps -d blog-web'
        