name: CI & CD

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setupt node
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    
    - name: Building project
      run: |
        touch .env
        echo "REACT_APP_API_BASEURL=https://api.segoqu.com" >> .env
        npm ci
        npm run test
        npm run build
        
    - name: Saving in cache
      uses: actions/cache@v2
      with:
        key: ${{ github.sha }}-build
        path: |
          ./build
          ./Dockerfile
          ./nginx.conf

  deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    needs: build
    
    steps:
    - name: Restoring from cache
      uses: actions/cache@v2
      with:
        key: ${{ github.sha }}-build
        path: |
          ./build
          ./Dockerfile
          ./nginx.conf
    
    - name: Configuring ssh
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        cat >> ~/.ssh/config <<END
        Host remote
          HostName $SSH_HOST
          Port $SSH_PORT
          User $SSH_USER
          IdentityFile ~/.ssh/id_rsa
          StrictHostKeyChecking no
        END
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
    
    - name: Creating project folder
      run: ssh remote "mkdir -p ~/$PROJECT_FOLDER/blog-web"
      env:
        PROJECT_FOLDER: ${{ secrets.PROJECT_FOLDER }}
    
    - name: Copying build
      run: rsync -az ./build remote:~/$PROJECT_FOLDER/blog-web
      env:
        PROJECT_FOLDER: ${{ secrets.PROJECT_FOLDER }}
    
    - name: Copying Dockerfile and nginx.conf
      run: |
        rsync -z ./Dockerfile remote:~/$PROJECT_FOLDER/blog-web/Dockerfile
        rsync -z ./nginx.conf remote:~/$PROJECT_FOLDER/blog-web/nginx.conf
      env:
        PROJECT_FOLDER: ${{ secrets.PROJECT_FOLDER }}
    
    - name: Running docker
      run: |
        ssh remote "docker-compose -f ~/$PROJECT_FOLDER/docker-compose.yml build blog-web"
        ssh remote "docker-compose -f ~/$PROJECT_FOLDER/docker-compose.yml --no-deps -d blog-web"
      env:
        PROJECT_FOLDER: ${{ secrets.PROJECT_FOLDER }}
        